#:kivy 1.1.0

<CamConfigScreen>:
    BackgroundBoxLayout:
        TabbedPanel:
            pos_hint: {'center_x': .5, 'center_y': .5}
            do_default_tab: False
            TabbedPanelItem:
                text: root.get_local_str("_cam_postion")
                CamConfig:
                    id: cam_config_distances
            TabbedPanelItem:
                text: root.get_local_str("_cam_config")
                MultipleCameras:
                    id: multi_cams_config